{
 "title": "GitHub activity",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "contributions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,24h,0),\n  sum(contributions) AS \"contributions\"\nFROM github_calendar\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,24h,0)"
    }
   ]
  },
  {
   "title": "total views breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,24h),\n  repo AS metric,\n  sum(total) AS \"total\"\nFROM github_stats\nWHERE\n  $__timeFilter(date) AND\n  type = 'views'\nGROUP BY 1,2\nORDER BY $__timeGroup(date,24h)"
    }
   ]
  },
  {
   "title": "total clones breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,24h),\n  repo AS metric,\n  sum(total) AS \"total\"\nFROM github_stats\nWHERE\n  $__timeFilter(date) AND\n  type = 'clones'\nGROUP BY 1,2\nORDER BY $__timeGroup(date,24h)"
    }
   ]
  },
  {
   "title": "views summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(date) AS \"time\",\n  CONCAT('<a href=\"http://github.com/', repo, '\" target=\"_blank\">', repo, \"</a>\") AS repo,\n  SUM(total) AS total,\n  SUM(uniques) AS uniques\nFROM github_stats\nWHERE\n  $__timeFilter(date)\n  AND type = \"views\"\nGROUP BY repo"
    },
    {
     "rawSql": "SELECT\n  MAX(date) AS \"time\",\n  \"<b>creaktive/*</b>\" AS repo,\n  SUM(total) AS total,\n  SUM(uniques) AS uniques\nFROM github_stats\nWHERE\n  $__timeFilter(date)\n  AND repo LIKE \"creaktive/%\"\n  AND type = \"views\""
    }
   ]
  },
  {
   "title": "clones summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(date) AS \"time\",\n  CONCAT('<a href=\"http://github.com/', repo, '\" target=\"_blank\">', repo, \"</a>\") AS repo,\n  SUM(total) AS total,\n  SUM(uniques) AS uniques\nFROM github_stats\nWHERE\n  $__timeFilter(date)\n  AND type = \"clones\"\nGROUP BY repo"
    },
    {
     "rawSql": "SELECT\n  MAX(date) AS \"time\",\n  \"<b>creaktive/*</b>\" AS repo,\n  SUM(total) AS total,\n  SUM(uniques) AS uniques\nFROM github_stats\nWHERE\n  $__timeFilter(date)\n  AND repo LIKE \"creaktive/%\"\n  AND type = \"clones\""
    }
   ]
  },
  {
   "title": "other metrics",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT('<a href=\"http://github.com/', repo, '\" target=\"_blank\">', repo, \"</a>\") AS repo,\n  watchers,\n  forks,\n  open_issues,\n  size\nFROM github_counts\nWHERE\n  DATE(date) = DATE(NOW());"
    },
    {
     "rawSql": "SELECT\n  \"<b>creaktive/*</b>\" AS repo,\n  SUM(watchers) AS watchers,\n  SUM(forks) AS forks,\n  SUM(open_issues) AS open_issues,\n  SUM(size) AS size\nFROM github_counts\nWHERE\n  DATE(date) = DATE(NOW())\n  AND repo LIKE \"creaktive/%\"\nGROUP BY DATE(date);"
    }
   ]
  }
 ]
}